### PR TITLE
IN-511 handle vcfs as additional files

### LINKED ISSUE #139: Handle VCFs as additional files
Can already handle delimited files in addition to the main vcf here: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/f596e57f56bbe811154fe9b2ab4335863b144968/resources/home/dnanexus/generate_workbook/utils/vcf.py#L318

Could add in ability to pass other vcfs in and do the minimum processing of splitting out fields but not filtering etc

### PR DESCRIPTION
**Pull request by jethror1**
- Handle VCFs passed to `--additional_files` (i.e from Pindel) and format them accordingly
  - Reuses a lot of the vcf methods for parsing and formatting
  - Change some of the vcf methods to return lists of vcfs instead of directly formatting the vcfs attribute to fit with the above
- Reformat the creation of Report text field to separate `vcf.format_report_text()` function to get rid of the mega lambda
- Minor formatting changes
- Fix borked tests from above changes
- Fixes #139

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/185)

### CODE REVIEW

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/185)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 442 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/185#-NtVNBcj5ABnz8OzwbJW:-NtVNBcj5ABnz8OzwbJX:byp9mux) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/300395cfabf3c8b15133ff6c51595f4fa4864f7b/resources/home/dnanexus/generate_workbook/utils/vcf.py#L442)):*
> ```Python
>                 # to get things like split INFO columns and hyperlinks
>                 file_df = splitColumns().split(file_df)
>                 file_df = self.make_report_text([file_df])[0]
> ```

will this work if the arg to make report is not set?

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/185)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 442 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/185#-NtVNBcj5ABnz8OzwbJW:-NtW0mGX3PsUbigmeKY3:b-60qyhq) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/300395cfabf3c8b15133ff6c51595f4fa4864f7b/resources/home/dnanexus/generate_workbook/utils/vcf.py#L442)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should be fine, I added a check to that function for the `Report text` column is present before changing the height, so it will just return from there:
```
            # first test if the Report text column is in the sheet
            if 'Report text' not in [x.value for x in curr_worksheet[1]]:
                continue

```
</blockquote></details>

makes sense. You also are indexing the first thing - is this the first additional file in your list of additional files?

**Review by Aisha-D — COMMENTED** [review]
The readme also needs update to state that VCFs are added as an additional sheets too - currently states tsv

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/185#-:-NtW1_yXAqnmPmH6r9vK:b-hskbb6)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jethror1)

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/185)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 442 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/185#-NtVNBcj5ABnz8OzwbJW:-NtW7CQb8MkmQUdBWxc3:bywf3qh) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/300395cfabf3c8b15133ff6c51595f4fa4864f7b/resources/home/dnanexus/generate_workbook/utils/vcf.py#L442)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

makes sense. You also are indexing the first thing - is this the first additional file in your list of additional files?
</blockquote></details>

how do you mean indexing? can you point me to the lines you're referring to

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/185)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 442 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/185#-NtVNBcj5ABnz8OzwbJW:-NtWIBBV-r0wYxM9ZD5Q:b-j90vl5) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/300395cfabf3c8b15133ff6c51595f4fa4864f7b/resources/home/dnanexus/generate_workbook/utils/vcf.py#L442)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

how do you mean indexing? can you point me to the lines you're referring to
</blockquote></details>

I was referring to this line and the following 4 lines really cause you keep repeating the element [0] then reading back into the same object. Also checked why you were indexing so the questions answered



_Code snippet:_
```Python
 file_df = self.make_report_text([file_df])[0]
 
```

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/185)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 442 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/185#-NtVNBcj5ABnz8OzwbJW:-NtWNWeT1alJA5QS2Xxm:b-fjjb7g) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/300395cfabf3c8b15133ff6c51595f4fa4864f7b/resources/home/dnanexus/generate_workbook/utils/vcf.py#L442)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

I was referring to this line and the following 4 lines really cause you keep repeating the element [0] then reading back into the same object. Also checked why you were indexing so the questions answered
</blockquote></details>

ahh because all of those return lists, but in this instance it's always going to be a single df since we loop over the files

**Review by jethror1 — COMMENTED** [review]
added more detail

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/185#-:-NtWNxy3E5BpVv7TAkwn:bw7ci5z)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

**Review by Aisha-D — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/185)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
