### PR TITLE
IN-510 unit test new features

### PR DESCRIPTION
**Pull request by Aisha-D**
- Update report text to only show field values if field exists in VCF
- Unit tests for report text and percent_af

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/192)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/192)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @Aisha-D)

___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 410 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/192#-NvkOuuH-W3OYC4cp1q2:-NvkOuuH-W3OYC4cp1q3:b93weyk) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/35aecfd81ce429ad06af33f7ab6d394d5311c6a4/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L410)):*
> ```Python
>         assert len(AF_column_percent) == len(contains_percent) , (
>             "Not all AFs are percent"
>         )
> ```

where you have multiple asserts in a test case, its better to use subtests (I like pytest subtest), this means that if the first assert fails the rest are still run instead of the test stopping: https://pypi.org/project/pytest-subtests/

example in some other unit tests: https://github.com/eastgenomics/trendyQC/blob/220dcd56bb6c267abc95956b04f5e24420b5f893/trendyqc/trend_monitoring/tests/test_multiqc.py#L195



_Code quote:_
```Python
        assert len(AF_column_percent) == len(contains_percent) , (
            "Not all AFs are percent"
        )
```
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 415 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/192#-NvkQsZw-N8hVQT1tqGF:-NvkQsZw-N8hVQT1tqGG:b-x3wqwm) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/35aecfd81ce429ad06af33f7ab6d394d5311c6a4/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L415)):*
> ```Python
>         # 2. check all greater than 0
>         res =  [s.replace('%','') for s in AF_column_percent]
>         res = [float(s) for s in res]
> ```

this you can directly just call float in the initial list comp: `[float(s.replace('%','')) for s in AF_column_percent]`



_Code quote:_
```Python
        res =  [s.replace('%','') for s in AF_column_percent]
        res = [float(s) for s in res]
```
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 416 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/192#-NvkQr1m1NoDLZb4XUP7:-NvkQr1m1NoDLZb4XUP8:b-58so6z) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/35aecfd81ce429ad06af33f7ab6d394d5311c6a4/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L416)):*
> ```Python
>         res =  [s.replace('%','') for s in AF_column_percent]
>         res = [float(s) for s in res]
>         print(res)
> ```

needed?



_Code quote:_
```Python
        print(res)
```
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 436 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/192#-NvkR5Ba0ZxCBseiFlUq:-NvkR5Ba0ZxCBseiFlUr:b-rbady6) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/35aecfd81ce429ad06af33f7ab6d394d5311c6a4/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L436)):*
> ```Python
>         for text in list(vcf_handler.vcfs[0].Report_text):
>             # check that the three HGVSc, HGVSp and VAF are listed
>             assert text.split(":")[0] == "Allele Frequency (VAF)", (
> ```

subtest again here to ensure all are checked

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/192)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 415 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/192#-NvkQsZw-N8hVQT1tqGF:-Nw9ID645oUluGfZQim3:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/35aecfd81ce429ad06af33f7ab6d394d5311c6a4/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L415)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this you can directly just call float in the initial list comp: `[float(s.replace('%','')) for s in AF_column_percent]`
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 416 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/192#-NvkQr1m1NoDLZb4XUP7:-Nw9IDzh5li6sYmDcWym:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/35aecfd81ce429ad06af33f7ab6d394d5311c6a4/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L416)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

needed?
</blockquote></details>

Done.

**Review by jethror1 — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/192)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @Aisha-D)

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/192)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @Aisha-D)

___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 415 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/192#-NvkQsZw-N8hVQT1tqGF:-Nw9UGi54ukslcPCP0xS:b-p9poot) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/35aecfd81ce429ad06af33f7ab6d394d5311c6a4/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L415)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

is it?

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/192)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 410 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/192#-NvkOuuH-W3OYC4cp1q2:-NwALfA65IboOceiVG0S:be9843z) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/35aecfd81ce429ad06af33f7ab6d394d5311c6a4/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L410)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

where you have multiple asserts in a test case, its better to use subtests (I like pytest subtest), this means that if the first assert fails the rest are still run instead of the test stopping: https://pypi.org/project/pytest-subtests/

example in some other unit tests: https://github.com/eastgenomics/trendyQC/blob/220dcd56bb6c267abc95956b04f5e24420b5f893/trendyqc/trend_monitoring/tests/test_multiqc.py#L195
</blockquote></details>

Done. I also learnt not to for loop within an assert function cause it wasnt working :upside_down_face: 
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 415 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/192#-NvkQsZw-N8hVQT1tqGF:-NwALbJ_9C8RXpPgtQeW:bz0jcb3) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/35aecfd81ce429ad06af33f7ab6d394d5311c6a4/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L415)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is it?
</blockquote></details>

duplicated below
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 436 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/192#-NvkR5Ba0ZxCBseiFlUq:-NwALYJBB17W6pmobV_-:b2f6nmv) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/35aecfd81ce429ad06af33f7ab6d394d5311c6a4/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L436)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

subtest again here to ensure all are checked
</blockquote></details>

done. (below)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/192)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
