### PR TITLE
Conditional colouring

### PR DESCRIPTION
**Pull request by jethror1**
Adds optional conditional colouring of cells in variant sheets from given input `column:condition:colour`  (e.g. `VF:<0.2&>=0.1:#a92f0c`)

Example colouring:

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`Readme.md` line 60 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127#-NJefpgbCp9XejtUaqhc:-NJefpgbCp9XejtUaqhd:b4bwfvu) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/fa950fbb1379a10fb93971228c5a80e8f9ddf3df/Readme.md#L60)):*
> ```Markdown
> `--additional_sheet_names` (`list`): Names to use for additional file sheets, if specified these MUST be the same number as the number of files passed and in the same order (`-iadditional_files=file1 -iadditional_files=file2 -iadditional_sheet_names='name_1 name_2'`). If not given, the first 31 characters of the filename will be used.
> 
> `--colour_cells` (`string`): Add conditional colouring of cells for a given column, this should be specified as column:value_range:colour, where colour is a valid hex value or colour name. Multiple conditions may be given in a single `value_range` for the same column and colour values by chaining multiple with either `&` for all or `|` for any condition. Example formats:
> ```

Please describe how to use this when combined with renaming of fields



_Code quote:_
```Markdown
--colour_cells
```

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @mattgarner)

___
*[`Readme.md` line 60 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127#-NJefpgbCp9XejtUaqhc:-NJehXP09icB0bh9LxzY:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/fa950fbb1379a10fb93971228c5a80e8f9ddf3df/Readme.md#L60)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Please describe how to use this when combined with renaming of fields
</blockquote></details>

Done.

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 664 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127#-NJfJidjE_AAIYDkjoZU:-NJfJidk1IZGP60QCR99:b3kvs4w) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/20fd984e315da4347d524f052463e01e0d74d18e/resources/home/dnanexus/generate_workbook/utils/excel.py#L664)):*
> ```Python
>         Arguments will be in the following formats:
>             - VF:>=0.9:green        => single condition
>             - VF:<0.8&>=0.6:orange  => both of two conditions
> ```

If we want the same colour to be applied to two ranges, can we do:
```
VF:<0.8&>=0.6:orange
VF:>0.2&<=0.4:orange
```
or does one replace the other for the same colour?



_Code quote:_
```Python
VF:<0.8&>=0.6:orange
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 665 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127#-NJfJFz5AvvbOasI_BuG:-NJfJFz5AvvbOasI_BuH:b-vv3z99) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/20fd984e315da4347d524f052463e01e0d74d18e/resources/home/dnanexus/generate_workbook/utils/excel.py#L665)):*
> ```Python
>             - VF:>=0.9:green        => single condition
>             - VF:<0.8&>=0.6:orange  => both of two conditions
>             - VF:>0.9|<0.1:red      => either of two conditions
> ```

`AF:<0.1|>0.9|>0.4&<0.6:green`
If I understand correctly then this will fail, and it's not entirely clear if it breaks the stated rules. 

Do we need to specify that only one operator can be applied in any single condition?



_Code quote:_
```Python
        Arguments will be in the following formats:
            - VF:>=0.9:green        => single condition
            - VF:<0.8&>=0.6:orange  => both of two conditions
            - VF:>0.9|<0.1:red      => either of two conditions
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 773 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127#-NJfL7cp3uAtkdkAQGe5:-NJfL7cp3uAtkdkAQGe6:bz3v6gz) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/20fd984e315da4347d524f052463e01e0d74d18e/resources/home/dnanexus/generate_workbook/utils/excel.py#L773)):*
> ```Python
>                                 patternType="solid",
>                                 start_color=colour
>                             )
> ```

Is it worth checking if the cell is already coloured before applying the new colour? 

This would indicate that you've messed up your criteria, since I assume the expectation is that you provide criteria which don't collide.

e.g. 

```
--colour "AF:>=0.2:orange" --colour "AF:<=0.2:green"
```
A cell with a value of 0.2 would be made orange, then green.



_Code quote:_
```Python
                        if to_colour:
                            worksheet[cell.coordinate].fill = PatternFill(
                                patternType="solid",
                                start_color=colour
                            )
```

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 664 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127#-NJfJidjE_AAIYDkjoZU:-NJfMOZT4qdYEMiQ63Wn:b4l19ec) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/20fd984e315da4347d524f052463e01e0d74d18e/resources/home/dnanexus/generate_workbook/utils/excel.py#L664)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

If we want the same colour to be applied to two ranges, can we do:
```
VF:<0.8&>=0.6:orange
VF:>0.2&<=0.4:orange
```
or does one replace the other for the same colour?
</blockquote></details>

Yes, pass 2 strings to `--colour`

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @mattgarner)

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 664 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127#-NJfJidjE_AAIYDkjoZU:-NJo2XKL7hNBF8FB-DpA:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/20fd984e315da4347d524f052463e01e0d74d18e/resources/home/dnanexus/generate_workbook/utils/excel.py#L664)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Yes, pass 2 strings to `--colour`
</blockquote></details>

Done.



_Code quote (from Readme.md):_
```Markdown
VF:>=0.9:green VF:<0.9&>=0.4:orange VF:>0.4:red
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 665 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127#-NJfJFz5AvvbOasI_BuG:-NJo30KXAhlW-1hsJ-Zx:bcwacnw) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/20fd984e315da4347d524f052463e01e0d74d18e/resources/home/dnanexus/generate_workbook/utils/excel.py#L665)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

`AF:<0.1|>0.9|>0.4&<0.6:green`
If I understand correctly then this will fail, and it's not entirely clear if it breaks the stated rules. 

Do we need to specify that only one operator can be applied in any single condition?
</blockquote></details>

have updated the readme to state this. Have also added a check when parsing arguments that any single expression doesn't contain both & and |, and added unit tests to show this works:

```
$ python3 -m pytest -vv resources/home/dnanexus/generate_workbook/tests/test_generate_workbook.py 
================================================== test session starts ===================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/jethro/Projects/eggd_generate_variant_workbook/resources/home/dnanexus/generate_workbook/tests, configfile: pytest.ini
plugins: Faker-14.0.0, mock-3.9.0, cov-4.0.0
collected 6 items                                                                                                        

resources/home/dnanexus/generate_workbook/tests/test_generate_workbook.py::TestVerifyImages::test_invalid_image_assertion PASSED [ 16%]
resources/home/dnanexus/generate_workbook/tests/test_generate_workbook.py::TestVerifyImages::test_differing_images_and_image_sheet_names PASSED [ 33%]
resources/home/dnanexus/generate_workbook/tests/test_generate_workbook.py::TestVerifyImages::test_differing_images_and_image_sizes PASSED [ 50%]
resources/home/dnanexus/generate_workbook/tests/test_generate_workbook.py::TestVerifyImages::test_invalid_image_sizes PASSED [ 66%]
resources/home/dnanexus/generate_workbook/tests/test_generate_workbook.py::TestVerifyColours::test_valid_colour_expressions PASSED [ 83%]
resources/home/dnanexus/generate_workbook/tests/test_generate_workbook.py::TestVerifyColours::test_invalid_colour_expression PASSED [100%]

=================================================== 6 passed in 0.46s ====================================================

```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 773 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127#-NJfL7cp3uAtkdkAQGe5:-NJkCmV_EwiZssa3Rlac:b-kbj829) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/20fd984e315da4347d524f052463e01e0d74d18e/resources/home/dnanexus/generate_workbook/utils/excel.py#L773)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Is it worth checking if the cell is already coloured before applying the new colour? 

This would indicate that you've messed up your criteria, since I assume the expectation is that you provide criteria which don't collide.

e.g. 

```
--colour "AF:>=0.2:orange" --colour "AF:<=0.2:green"
```
A cell with a value of 0.2 would be made orange, then green.
</blockquote></details>

could do yes, do you think this should fail or just print a warning and not change the colour?

not sure of a reliable way to test if there are any overlaps in value ranges for a given column, or to just make it a warning and not do it wrong

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @mattgarner)

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 773 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127#-NJfL7cp3uAtkdkAQGe5:-NJtLunJ4RzcgT0t3J9m:b-bt82xv) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/20fd984e315da4347d524f052463e01e0d74d18e/resources/home/dnanexus/generate_workbook/utils/excel.py#L773)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

could do yes, do you think this should fail or just print a warning and not change the colour?

not sure of a reliable way to test if there are any overlaps in value ranges for a given column, or to just make it a warning and not do it wrong
</blockquote></details>

I have added a warning in for now, tested by passing the same colouring twice with `--colour 'VF:>=0.9:#0b7b0d' 'VF:>=0.9:#0b7b0d'`:

```

Writing 34 rows to included sheet (1/2)

################################### WARNING ###################################

Overlapping colouring of cells, the following cells colour were not changed due 
to being previously coloured:

        Current cell colour: 000b7b0d
        New cell colour: 0b7b0d
        Cells not coloured: ['I16', 'I17', 'I18', 'I19', 'I20']


###############################################################################
Writing to Excel for sheet included took 0s

Verifying data written to file for included sheet...


Writing 2120 rows to excluded sheet (2/2)

################################### WARNING ###################################

Overlapping colouring of cells, the following cells colour were not changed due 
to being previously coloured:

        Current cell colour: 000b7b0d
        New cell colour: 0b7b0d
        Cells not coloured: I3, I4, I5, I8, I9 + 900 more cells


###############################################################################
Writing to Excel for sheet excluded took 5s

Verifying data written to file for excluded sheet...

Done!
```

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 773 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127#-NJfL7cp3uAtkdkAQGe5:-NKrTzd6EUNjwjLlhzdy:bz2nq8b) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/20fd984e315da4347d524f052463e01e0d74d18e/resources/home/dnanexus/generate_workbook/utils/excel.py#L773)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I have added a warning in for now, tested by passing the same colouring twice with `--colour 'VF:>=0.9:#0b7b0d' 'VF:>=0.9:#0b7b0d'`:

```

Writing 34 rows to included sheet (1/2)

################################### WARNING ###################################

Overlapping colouring of cells, the following cells colour were not changed due 
to being previously coloured:

        Current cell colour: 000b7b0d
        New cell colour: 0b7b0d
        Cells not coloured: ['I16', 'I17', 'I18', 'I19', 'I20']


###############################################################################
Writing to Excel for sheet included took 0s

Verifying data written to file for included sheet...


Writing 2120 rows to excluded sheet (2/2)

################################### WARNING ###################################

Overlapping colouring of cells, the following cells colour were not changed due 
to being previously coloured:

        Current cell colour: 000b7b0d
        New cell colour: 0b7b0d
        Cells not coloured: I3, I4, I5, I8, I9 + 900 more cells


###############################################################################
Writing to Excel for sheet excluded took 5s

Verifying data written to file for excluded sheet...

Done!
```
</blockquote></details>

Could we make this fail rather than warn please?

If it were to happen then something is wrong, which I think warrants a fail.

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/127)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
