### PR TITLE
Function for downdowns

### PR DESCRIPTION
**Pull request by wintun12**
Adding dropdowns function to the workbook.

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @wintun12)

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 21 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0YriH1DubXT_6tQcG:-Nm0YriH1DubXT_6tQcH:bgqyki9) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L21)):*
> ```Python
> 
> from .utils import is_numeric
> from openpyxl.worksheet.datavalidation import DataValidation
> ```

can this be beneath the other openpyxl imports to fit with pep8, general convention is for these to be alphanumeric and follow:

- standard library imports
- install package imports (i.e like openpyxl)
- relative imports (i.e from other local scripts)



_Code quote:_
```Python
from openpyxl.worksheet.datavalidation import DataValidation
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1409 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0izgh37zSU1Zj7OGI:-Nm0izgi5RFne4WWE04_:brmur6o) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1409)):*
> ```Python
>         """
>         function to add drop-downs in report and included sheets
>         in report sheet, drop-downs are added for the strength
> ```

Could this be changed slightly to something like:
```
Function to add drop-downs in the report tab for entering ACMG criteria for classification, as well as a boolean drop down into the additional 'Interpreted' column of the variant sheet(s). 
```



_Code quote:_
```Python
        function to add drop-downs in report and included sheets
        in report sheet, drop-downs are added for the strength
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1415 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0Zh3Y2HPFwGSbN6fQ:-Nm0Zh3Y2HPFwGSbN6fR:bptgvqw) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1415)):*
> ```Python
>         """
>         wb = load_workbook(filename=self.args.output)
>         # adding dropdown for strenght in report table
> ```

typo, the spellcheck extension for VSCode (if you're using that editor), is pretty good at picking up typos ad might be useful: 

https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker



_Code quote:_
```Python
strenght
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1416 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0aPKiBS3DwPFI9boP:-Nm0aPKiBS3DwPFI9boQ:b-gzk6zu) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1416)):*
> ```Python
>         wb = load_workbook(filename=self.args.output)
>         # adding dropdown for strenght in report table
>         ws_re = wb['report']
> ```

I know the convention for openpyxl is to use `wb` and `ws` for workbook and worksheet as variables (and I have done the same), but can you make these slightly more verbose (i.e. `ws_re` -> `report_sheet`), short less descriptive variable names makes it harder to read (and in this case using `re` is more confusing in Python since that's usually reserved for regex)  



_Code quote:_
```Python
ws_re
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1426 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0_Crp4e-ushBeV5N8:-Nm0_Crp4e-ushBeV5N9:bb7phvt) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1426)):*
> ```Python
>         cell_for_strenght = ['J8', 'J11', 'J12', 'J15', 'J16', 'J17', 'J20',
>                              'J21', 'J22', 'J23', 'J24', 'J25']
>         for cell in cell_for_strenght:
> ```

typo



_Code quote:_
```Python
cell_for_strenght
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1430 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0_aNn8hMizWWGLKu6:-Nm0_aNn8hMizWWGLKu7:bjubc0x) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1430)):*
> ```Python
>         strength_val.showInputMessage = True
>         strength_val.showErrorMessage = True
>         # adding final classification dropdown
> ```

as a minor style point to help with readability, could you add a few more blank lines (maybe between each few blocks of code relating to different operations, such as where your comments are)



_Code quote:_
```Python
# adding final classification dropdown
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1449 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0a4k31-WklcYZHqU_:-Nm0a4k31-WklcYZHqUa:b-xsfsag) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1449)):*
> ```Python
>         class_val.showInputMessage = True
>         class_val.showErrorMessage = True
>         # adding Interpreted column dropdown in included tab
> ```

this won't always necessarily be named included, if filtering is not performed (such as in CNV reports) this tab is named just 'reports'. Can this just be the 'first variant sheet tab'



_Code quote:_
```Python
included
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1450 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0b1vw16DDVpI4GASA:-Nm0b1vxByfQiSp4PeYs:bpgi4ja) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1450)):*
> ```Python
>         class_val.showErrorMessage = True
>         # adding Interpreted column dropdown in included tab
>         ws_in = wb[self.args.sheets[0]]
> ```

for variable naming, can this be something like `first_variant_sheet`



_Code quote:_
```Python
ws_in
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1451 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0bC5hBXC25MdP9TI8:-Nm0bC5hBXC25MdP9TI9:b-fi9jdq) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1451)):*
> ```Python
>         # adding Interpreted column dropdown in included tab
>         ws_in = wb[self.args.sheets[0]]
>         ws_in['AS1'] = 'Interpreted'
> ```

is this explicitly making the column `AS` be `Interpreted`? This isn't ideal if so as it won't be robust if new INFO fields are added / removed from the VCF (especially if more are added as I assume it will overwrite what is in the column).

Do we also know that the scientists definitely want this at the end? If it is hardcoded like this we won't be able to change it from the config, and would require a change to the app to modify it. I think it would be better to have the check for `if self.args.summary == 'Dias'` [here](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b1daf06aa2fb59bbe81b99e70d780cf09f1bafb4/resources/home/dnanexus/generate_workbook/utils/vcf.py#L158) like is done for the comment column so that it can be controlled through other inputs, then in this function you can pick it up from the columns to get the appropriate column and add in the data validation.



_Code quote:_
```Python
ws_in['AS1']
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1461 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0dawi-fzSwJfx52hs:-Nm0dawj7OosfKQqbOcC:bjnweua) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1461)):*
> ```Python
>         ws_in.add_data_validation(data_val)
>         num_variant = self.vcfs[0].shape[0]
>         for i in range(0, num_variant):
> ```

range defaults to starting at zero, so this can be `for i in range(num_variant):`



_Code quote:_
```Python
for i in range(0, num_variant):
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1462 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0e5AP5g3XNplrziYS:-Nm0e5AP5g3XNplrziYT:b4zwct9) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1462)):*
> ```Python
>         num_variant = self.vcfs[0].shape[0]
>         for i in range(0, num_variant):
>             data_val.add(ws_in["AS"+str(i+2)])
> ```

why is this `+2`?



_Code quote:_
```Python
str(i+2)
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1465 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0bdGr3ywhatQikJLU:-Nm0bdGr3ywhatQikJLV:bcfg348) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1465)):*
> ```Python
>         data_val.showInputMessage = True
>         data_val.showErrorMessage = True
>         ws_in['AT1'] = 'Comment'
> ```

adding an empty comment column is already an optional input for the app and will be created and handled by the other methods such as rearranging columns: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b1daf06aa2fb59bbe81b99e70d780cf09f1bafb4/dxapp.json#L128

I think these lines can go and using `-iadd_comment_column=true` should add this as you want, an example of inputs we have set in the config for this app are here: https://github.com/eastgenomics/egg4_dias_TWE_config/blob/3e8e29362f1f9c9216495aeae710bd8a75f714a9/egg4_config_v2.1.5.py#L60



_Code quote:_
```Python
ws_in['AT1'] = 'Comment'
```

**Review by wintun12 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 21 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0YriH1DubXT_6tQcG:-Nm1dR6i0E83E1k_qjsD:b-hw0rfz) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L21)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can this be beneath the other openpyxl imports to fit with pep8, general convention is for these to be alphanumeric and follow:

- standard library imports
- install package imports (i.e like openpyxl)
- relative imports (i.e from other local scripts)
</blockquote></details>

Moved as suggested 
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1409 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0izgh37zSU1Zj7OGI:-Nm1dd5k6TqP-XPMPFLZ:b-e36xvi) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1409)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

Could this be changed slightly to something like:
```
Function to add drop-downs in the report tab for entering ACMG criteria for classification, as well as a boolean drop down into the additional 'Interpreted' column of the variant sheet(s). 
```
</blockquote></details>

Rephrased as suggested
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1415 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0Zh3Y2HPFwGSbN6fQ:-Nm1dfe2BENk6_lcc0yp:bombt9c) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1415)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

typo, the spellcheck extension for VSCode (if you're using that editor), is pretty good at picking up typos ad might be useful: 

https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker
</blockquote></details>

Corrected typo
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1416 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0aPKiBS3DwPFI9boP:-Nm1dhGk-sI1tNmQZFNL:bqtnumq) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1416)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I know the convention for openpyxl is to use `wb` and `ws` for workbook and worksheet as variables (and I have done the same), but can you make these slightly more verbose (i.e. `ws_re` -> `report_sheet`), short less descriptive variable names makes it harder to read (and in this case using `re` is more confusing in Python since that's usually reserved for regex)
</blockquote></details>

rename the variable name as suggested
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1426 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0_Crp4e-ushBeV5N8:-Nm1dkff-PP3Lf8kl4j2:bombt9c) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1426)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Corrected typo
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1430 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0_aNn8hMizWWGLKu6:-Nm1dnEEAkETfKbL_oly:b-ttcf15) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1430)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

as a minor style point to help with readability, could you add a few more blank lines (maybe between each few blocks of code relating to different operations, such as where your comments are)
</blockquote></details>

added blank lines as suggested
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1449 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0a4k31-WklcYZHqU_:-Nm1drOs716QxfTIsHMU:b-e36xvi) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1449)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this won't always necessarily be named included, if filtering is not performed (such as in CNV reports) this tab is named just 'reports'. Can this just be the 'first variant sheet tab'
</blockquote></details>

Rephrased as suggested
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1450 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0b1vw16DDVpI4GASA:-Nm1dugp7mu-eZihbNfp:b7hd9hw) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1450)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

for variable naming, can this be something like `first_variant_sheet`
</blockquote></details>

Renamed as suggested
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1461 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0dawi-fzSwJfx52hs:-Nm1dxc64dWjWFvqnUEc:b-whovh2) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1461)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

range defaults to starting at zero, so this can be `for i in range(num_variant):`
</blockquote></details>

removed 0 as suggested

**Review by wintun12 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160)* status: 0 of 2 files reviewed, 12 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1451 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0bC5hBXC25MdP9TI8:-Nm1k0tF9hNy_s_V3qaV:b-f71wfq) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1451)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this explicitly making the column `AS` be `Interpreted`? This isn't ideal if so as it won't be robust if new INFO fields are added / removed from the VCF (especially if more are added as I assume it will overwrite what is in the column).

Do we also know that the scientists definitely want this at the end? If it is hardcoded like this we won't be able to change it from the config, and would require a change to the app to modify it. I think it would be better to have the check for `if self.args.summary == 'Dias'` [here](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b1daf06aa2fb59bbe81b99e70d780cf09f1bafb4/resources/home/dnanexus/generate_workbook/utils/vcf.py#L158) like is done for the comment column so that it can be controlled through other inputs, then in this function you can pick it up from the columns to get the appropriate column and add in the data validation.
</blockquote></details>

added the Reported col (this is same as Interpreted col, I just rename as Reported because I thought it is more meaningful) in the vcf.py instead of excel.py as before.
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1465 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0bdGr3ywhatQikJLU:-Nm1jmCx2XNNaz7ZUVfV:b-jtk478) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1465)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

adding an empty comment column is already an optional input for the app and will be created and handled by the other methods such as rearranging columns: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b1daf06aa2fb59bbe81b99e70d780cf09f1bafb4/dxapp.json#L128

I think these lines can go and using `-iadd_comment_column=true` should add this as you want, an example of inputs we have set in the config for this app are here: https://github.com/eastgenomics/egg4_dias_TWE_config/blob/3e8e29362f1f9c9216495aeae710bd8a75f714a9/egg4_config_v2.1.5.py#L60
</blockquote></details>

removed a few lines that add empty col of 'Comment'

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @wintun12)

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1451 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0bC5hBXC25MdP9TI8:-Nm5gKpV7O1B8xMBsS27:bjrri5l) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1451)):*
<details><summary><i>Previously, wintun12 wrote…</i></summary><blockquote>

added the Reported col (this is same as Interpreted col, I just rename as Reported because I thought it is more meaningful) in the vcf.py instead of excel.py as before.
</blockquote></details>

I'm not sure we want it called Reported since they are different things, we won't usually report benign variants but they may be interpreted. Can we switch it back to Interpreted and double check with matt/wook/liv what the scientists / we want?
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1474 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm5k8OjBYpxIb83cjmf:-Nm5k8OjBYpxIb83cjmg:b54zaqs) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/0eb9988a4fb9d76cf0971f2d5ba817b0ae78d629/resources/home/dnanexus/generate_workbook/utils/excel.py#L1474)):*
> ```Python
>         worksheet: openpyxl.Writer
>                writer object of current sheet
>         """    
> ```

missing return from docstring



_Code quote:_
```Python
   """
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1478 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm5kBB79AinvNf7DYhR:-Nm5kBB79AinvNf7DYhS:b7uecse) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/0eb9988a4fb9d76cf0971f2d5ba817b0ae78d629/resources/home/dnanexus/generate_workbook/utils/excel.py#L1478)):*
> ```Python
>             if column_cell[0].value == 'Reported':
>                 col = str(column_cell[0])
>                 col_value = col.split('.')[1].split('>')[0][:-1]
> ```

what is the need for the splitting? is this returning the `AS1` or similar? 



_Code quote:_
```Python
col_value = col.split('.')[1].split('>')[0][:-1]
```
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 162 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm5kPslCdIWWzfazhpB:-Nm5kPslCdIWWzfazhpC:b-8iqb7b) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/0eb9988a4fb9d76cf0971f2d5ba817b0ae78d629/resources/home/dnanexus/generate_workbook/utils/vcf.py#L162)):*
> ```Python
>             # if it is dias pipeline, add the empty col
>             # named Reported in the first variant sheet
>             self.vcfs[0]['Reported']=''
> ```

as above, can this be `Interpreted` please



_Code quote:_
```Python
Reported
```

**Review by wintun12 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1451 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm0bC5hBXC25MdP9TI8:-Nm5pVdm2XtGTmtVdZnu:b-a67ntl) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/b958c590e95656a3769c9c2c7a4418e30050afa5/resources/home/dnanexus/generate_workbook/utils/excel.py#L1451)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I'm not sure we want it called Reported since they are different things, we won't usually report benign variants but they may be interpreted. Can we switch it back to Interpreted and double check with matt/wook/liv what the scientists / we want?
</blockquote></details>

Reported was changed back to Interpreted. 
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1474 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm5k8OjBYpxIb83cjmf:-Nm5pavl6vuI4Nf_30Sn:b-9yqv0n) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/0eb9988a4fb9d76cf0971f2d5ba817b0ae78d629/resources/home/dnanexus/generate_workbook/utils/excel.py#L1474)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

missing return from docstring
</blockquote></details>

added return in docstring
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1478 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm5kBB79AinvNf7DYhR:-Nm5pevfBNgbP4_uIDvl:bpxh7hz) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/0eb9988a4fb9d76cf0971f2d5ba817b0ae78d629/resources/home/dnanexus/generate_workbook/utils/excel.py#L1478)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what is the need for the splitting? is this returning the `AS1` or similar?
</blockquote></details>

`col` returns like `<Cell 'included'.AT1>`. I want `col_value` as `AT` only so I split it. 
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 162 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm5kPslCdIWWzfazhpB:-Nm5qD8rAJMiXbTMkNd_:bo1vd1r) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/0eb9988a4fb9d76cf0971f2d5ba817b0ae78d629/resources/home/dnanexus/generate_workbook/utils/vcf.py#L162)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

as above, can this be `Interpreted` please
</blockquote></details>

Changed back to Interpreted

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @wintun12)

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1478 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm5kBB79AinvNf7DYhR:-Nm6DzJZ6Z4TX25PHRIo:bmwcpav) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/0eb9988a4fb9d76cf0971f2d5ba817b0ae78d629/resources/home/dnanexus/generate_workbook/utils/excel.py#L1478)):*
<details><summary><i>Previously, wintun12 wrote…</i></summary><blockquote>

`col` returns like `<Cell 'included'.AT1>`. I want `col_value` as `AT` only so I split it.
</blockquote></details>

I'm pretty sure `column_cell[0]` here will be an openpyxl Cell object, meaning the column letter (i.e. `AT`) will be accessible as `column_cell[0].column_letter`: https://openpyxl.readthedocs.io/en/stable/api/openpyxl.cell.cell.html?highlight=cell#openpyxl.cell.cell.Cell

**Review by wintun12 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1478 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160#-Nm5kBB79AinvNf7DYhR:-Nm6IA963u322RXvBbtD:batpji7) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/0eb9988a4fb9d76cf0971f2d5ba817b0ae78d629/resources/home/dnanexus/generate_workbook/utils/excel.py#L1478)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I'm pretty sure `column_cell[0]` here will be an openpyxl Cell object, meaning the column letter (i.e. `AT`) will be accessible as `column_cell[0].column_letter`: https://openpyxl.readthedocs.io/en/stable/api/openpyxl.cell.cell.html?highlight=cell#openpyxl.cell.cell.Cell
</blockquote></details>

Definitely it is. Updated as suggested.

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wintun12)

**Pull request merged**
