### PR TITLE
adding_locking_function

### PR DESCRIPTION
**Pull request by wintun12**
Changes:
- excel.py - added locking function for all sheets
- update reame and dxapp.json files to include the command line arguments
- update code.sh to add new arguments
- update generate_workbook.py to add args

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163)* status: 0 of 5 files reviewed, 9 unresolved discussions (waiting on @wintun12)

___
*[`dxapp.json` line 278 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NoppAV21S7ItxXg81sG:-NoppAV21S7ItxXg81sH:b-4omqmk) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/dxapp.json#L278)):*
> ```JSON
>       "class": "int",
>       "optional": true,
>       "default": 200,
> ```

why are you defaulting to unlock 200 rows? can this not be a bool to just lock the sheet or not and then select the columns where we have data? is this locking only being used for the ACMG reporting sheet and does it even need to be controllable?



_Code quote:_
```JSON
"default": 200,
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 570 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NopoG3B1kv92A-k-boq:-NopoG3B1kv92A-k-bor:b-84ieyh) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L570)):*
> ```Python
>                           ]
>         self.lock_sheet(self.summary, cell_to_unlock, self.summary.max_row+1,
>                         10, self.args.row_to_unlock, self.args.col_to_unlock)
> ```

when you're calling functions with more than a couple of arguments it can make it more readable to specify as named args like:
```
self.lock_sheet(
    ws=self.summary,
    cell_to_unlock=cell_to_unlock,
    start_row=self.summary.max_row+1
    ....

```



_Code quote:_
```Python
        self.lock_sheet(self.summary, cell_to_unlock, self.summary.max_row+1,
                        10, self.args.row_to_unlock, self.args.col_to_unlock)
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 774 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NopqCtu1qs3l2ChOAdx:-NopqCtu1qs3l2ChOAdy:b-ussc8e) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L774)):*
> ```Python
>                           "L16", "L17", "L20", "L21", "L22", "L23", "L24",
>                           "H25"]
>         self.lock_sheet(report, cell_to_unlock, report.max_row+1,
> ```

as above with named args



_Code quote:_
```Python
self.lock_sheet(report, cell_to_unlock, report.max_row+1,
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 848 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NopooQH38rryQLWCnib:-NopooQH38rryQLWCnic:bcfomef) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L848)):*
> ```Python
>                     num_variant = vcf.shape[0]
>                     cell_to_unlock = []
>                     for row in range(2, num_variant+2):
> ```

why this range?



_Code quote:_
```Python
2, num_variant+2
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1591 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NoppUybChZ6ACtKk0Cf:-NoppUybChZ6ACtKk0Cg:bsc7m09) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L1591)):*
> ```Python
>         """
>         ws.protection.sheet = True
>         ws.protection.password = "sheet_is_protected"
> ```

I think you can lock without a password, why does then just require a unticking a check box for them to unlock it, are we sure we want to lock with a password vs just locking editing?



_Code quote:_
```Python
 ws.protection.password = "sheet_is_protected"
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1600 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NoppiWl4vLQ5-gWKWon:-NoppiWl4vLQ5-gWKWoo:b-9qbczw) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L1600)):*
> ```Python
>         for col in range(1, start_col+unlock_col_num):
>             for row in range(start_row, start_row+unlock_row_num):
>                 col_letter = get_column_letter(col)
> ```

this shouldn't be called inside the loop over rows since its being called for every row instead of once per column



_Code quote:_
```Python
col_letter = get_column_letter(col)
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1604 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-Nopq2T6CV__NpFTSyiX:-Nopq2T6CV__NpFTSyiY:bh83mof) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L1604)):*
> ```Python
>                 cell = f"{col_letter}{row_num}"
>                 ws[cell].protection = Protection(locked=False)
>         for col in range(start_col, start_col+unlock_col_num):
> ```

can this loop over the columns being combined with the above to prevent looping over the columns?
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1606 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NoppvpdEtECF2_6cptS:-Noppvpe5TMxesDovWEX:b-rs3v5g) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L1606)):*
> ```Python
>         for col in range(start_col, start_col+unlock_col_num):
>             for row in range(1, start_row):
>                 col_letter = get_column_letter(col)
> ```

same here, move outside this for loop



_Code quote:_
```Python
col_letter = get_column_letter(col)
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1630 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NopnhvU1dx6LUBvtDz5:-NopnhvU1dx6LUBvtDz6:bx8maxg) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L1630)):*
> ```Python
>                 col_letter = column_cell[0].column_letter
> 
>         return col_letter
> ```

if the specified `col_name` doesn't exist in the sheet, this would raise a `NameError` as the `col_letter` variable wouldn't be defined since its inside the conditional.

Are we sure wherever this function is called the column will exist (i.e. are you only ever looping over columns read from the sheet/dataframe?). if not, it would be better to initialise the `col_letter` variable to None first, then if the specified column isn't found it will return None for the column letter

**Review by wintun12 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163)* status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @jethror1)

___
*[`dxapp.json` line 278 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NoppAV21S7ItxXg81sG:-Np0JoeI7wCDaKP26Pky:b-ybzkok) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/dxapp.json#L278)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why are you defaulting to unlock 200 rows? can this not be a bool to just lock the sheet or not and then select the columns where we have data? is this locking only being used for the ACMG reporting sheet and does it even need to be controllable?
</blockquote></details>

Removed this part and just add bool to lock or unlock. 
200 rows and columns are now put as fixed variable. I checked with Matt and he agrees with 200. That 200 rows and columns are for the number of rows and columns to be unlocked below and right next to the populated table which is locked. I attached a sketch which might explain a bit clearer. And the locking is for all sheets (not only report sheet)

-The left upper is our populated table which is locked with some specific cells unlocked.  
-Next to the table (200 columns -striped in red) and (200 rows -striped in blue) are unlocked for any writing/screenshots.


___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 570 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NopoG3B1kv92A-k-boq:-Np0Kv_ACeVR3ERsBjqR:b5te3e) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L570)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

when you're calling functions with more than a couple of arguments it can make it more readable to specify as named args like:
```
self.lock_sheet(
    ws=self.summary,
    cell_to_unlock=cell_to_unlock,
    start_row=self.summary.max_row+1
    ....

```
</blockquote></details>

added as suggested
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 774 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NopqCtu1qs3l2ChOAdx:-Np0KyBGEiMHN4m9tpMc:b5te3e) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L774)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

as above with named args
</blockquote></details>

added as suggested
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 848 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NopooQH38rryQLWCnib:-Np0L-E6BHu9PA7c_NHk:b-8brul2) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L848)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why this range?
</blockquote></details>

i want to unlock for all rows with variant (in `Comment` and `Interpreted` column). Variant always start from row 2 (as row 1 is column title). So I think I need to add `+2`. For example, I got two variants, so I need to start unlock from row 2 up to row 3 for two variants. So,  I think I need range from (2, 4) which is always +2 for num_variant. 
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1591 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NoppUybChZ6ACtKk0Cf:-Np0LpIg2_aaxOs8nDdK:b-bkmm6w) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L1591)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I think you can lock without a password, why does then just require a unticking a check box for them to unlock it, are we sure we want to lock with a password vs just locking editing?
</blockquote></details>

For this, I have checked with Matt. Will make changes when he replies. 
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1600 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NoppiWl4vLQ5-gWKWon:-Np0LvTvAFQrd8Mj4lVj:b-mw03fw) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L1600)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this shouldn't be called inside the loop over rows since its being called for every row instead of once per column
</blockquote></details>

called outside the loop now. 
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1604 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-Nopq2T6CV__NpFTSyiX:-Np0M5Wc0Y8H_LrQEaI6:btpzh93) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L1604)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can this loop over the columns being combined with the above to prevent looping over the columns?
</blockquote></details>

I am not quite sure how I can combine the two loops if I understand correctly what you meant.
As in the sketch that I attached above, the first `for` loop is to unlock the region below the table (blue one). For this one, the column starts from 1 and ends in start_col+200. `start_col` is the one col right after the max_col of populated table. And the row start from the `start_row` and ends in `start_row+200`. Again, `start_row` here is one row right below max_row of populated table.

And the second for loop is to unlock the region right to the table (red one) in sketch. For that one, the col start from `start_col` and ends at `start_col+200. For the row, it starts from 1 and ends in `start_row` because the rows below `start_row` are already unlocked from the first `for` loop. 
Sorry, what I said might be a few confusing. I put the snippet below. Please do let me know if any que.



_Code snippet:_
```Python
# first for loop I am talking about 
        for col in range(1, start_col+unlock_col_num):
            col_letter = get_column_letter(col)
            for row in range(start_row, start_row+unlock_row_num):
                row_num = row
                cell = f"{col_letter}{row_num}"
                ws[cell].protection = Protection(locked=False)
                
# second for loop I am talking about 
        for col in range(start_col, start_col+unlock_col_num):
            col_letter = get_column_letter(col)
            for row in range(1, start_row):
                row_num = row
                cell = f"{col_letter}{row_num}"
                ws[cell].protection = Protection(locked=False)
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1606 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NoppvpdEtECF2_6cptS:-Np0LzWT0ybPHNLoeYXN:b-85jzby) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L1606)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

same here, move outside this for loop
</blockquote></details>

called outside the loop now
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1630 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NopnhvU1dx6LUBvtDz5:-Np0M1ef4JqbazT9cEQh:bdml9c9) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L1630)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if the specified `col_name` doesn't exist in the sheet, this would raise a `NameError` as the `col_letter` variable wouldn't be defined since its inside the conditional.

Are we sure wherever this function is called the column will exist (i.e. are you only ever looping over columns read from the sheet/dataframe?). if not, it would be better to initialise the `col_letter` variable to None first, then if the specified column isn't found it will return None for the column letter
</blockquote></details>

put 'None' as suggested. 
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 584 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-Np0PPvl9FUu2DT7AN_S:-Np0PPvl9FUu2DT7AN_T:b-yve2tr) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9d0d3e09be1b82427e77a11c303b059c6824c56d/resources/home/dnanexus/generate_workbook/utils/excel.py#L584)):*
> ```Python
>         ACMG criteria
>         """
>         report = self.workbook.create_sheet(f"interpret_{report_sheet_num}")
> ```

Here I rename `report_` as `interpret_` as Wook asked me to do so. 



_Code quote:_
```Python
 report = self.workbook.create_sheet(f"interpret_{report_sheet_num}")
```

**Review by wintun12 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163)* status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1591 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NoppUybChZ6ACtKk0Cf:-Np4Eb6g5NDKL7TJdnxr:b-tqy1fl) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L1591)):*
<details><summary><i>Previously, wintun12 wrote…</i></summary><blockquote>

For this, I have checked with Matt. Will make changes when he replies.
</blockquote></details>

I checked with Matt and he confirmed we want to lock with password so that the scientists cannot unlock at the end. If they really need to unlock, we can provide the password to them. So, I will leave password line in the script.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @wintun12)

___
*[`dxapp.json` line 278 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NoppAV21S7ItxXg81sG:-NpKA7FX4GZrtlsLdqOn:b-ffxc9y) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/dxapp.json#L278)):*
<details><summary><i>Previously, wintun12 wrote…</i></summary><blockquote>

Removed this part and just add bool to lock or unlock. 
200 rows and columns are now put as fixed variable. I checked with Matt and he agrees with 200. That 200 rows and columns are for the number of rows and columns to be unlocked below and right next to the populated table which is locked. I attached a sketch which might explain a bit clearer. And the locking is for all sheets (not only report sheet)

-The left upper is our populated table which is locked with some specific cells unlocked.  
-Next to the table (200 columns -striped in red) and (200 rows -striped in blue) are unlocked for any writing/screenshots.


</blockquote></details>

ah that makes sense, can you update the help string to specify this only locks the ACMG reporting sheet and not all, or is it used elsewhere?
___
*[`Readme.md` line 101 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NpKAF1Z8G7W-uR-i4zR:-NpKAF1Z8G7W-uR-i4zS:bt6c2b8) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9d0d3e09be1b82427e77a11c303b059c6824c56d/Readme.md#L101)):*
> ```Markdown
> `--split_hgvs` (`bool`): If true, the c. and p. changes in HGVSc and HGVSp will be split out into DNA and Protein columns respectively, without the transcript
> 
> `--lock_sheet` (`bool`): If true, the workbook sheets are locked
> ```

same as above to add more detail
___
*[`resources/home/dnanexus/generate_workbook/generate_workbook.py` line 242 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NpKAIqw5448KKAWtn5t:-NpKAIqxBaBaw0pySCyi:b-9chp70) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9d0d3e09be1b82427e77a11c303b059c6824c56d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L242)):*
> ```Python
>         parser.add_argument(
>             '--lock_sheet', action='store_true',
>             help='lock sheets in the workbook'
> ```

as above



_Code quote:_
```Python
 help='lock sheets in the workbook'
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 848 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NopooQH38rryQLWCnib:-NpKBVsb9s6hmmS52Nn7:b-1f0frd) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L848)):*
<details><summary><i>Previously, wintun12 wrote…</i></summary><blockquote>

i want to unlock for all rows with variant (in `Comment` and `Interpreted` column). Variant always start from row 2 (as row 1 is column title). So I think I need to add `+2`. For example, I got two variants, so I need to start unlock from row 2 up to row 3 for two variants. So,  I think I need range from (2, 4) which is always +2 for num_variant.
</blockquote></details>

ahhh okay, if either of those columns aren't present (i.e. if we reun the app without `--add_comment_column` specified, then `comment_col` would be None and your `cell_to_unlock` would end up being `None2`), I assume this would raise an error? should you check that was is retured from `get_col_letter()` is not None first?
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 32 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NpKANHd3LbV0-lRBNKE:-NpKANHeDQyvUYlIs_pX:b42lrx4) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9d0d3e09be1b82427e77a11c303b059c6824c56d/resources/home/dnanexus/generate_workbook/utils/excel.py#L32)):*
> ```Python
> 
> DEFAULT_FONT.name = 'Calibri'
> ROW_TO_UNLOCK = 200
> ```

can this have a comment to mention where it's being used and what for

**Review by wintun12 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @jethror1)

___
*[`dxapp.json` line 278 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NoppAV21S7ItxXg81sG:-NpKSBDP65-We9t6iyhg:bckefyj) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/dxapp.json#L278)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

ah that makes sense, can you update the help string to specify this only locks the ACMG reporting sheet and not all, or is it used elsewhere?
</blockquote></details>

Hi, Jethro the locking is for all sheets - not only ACMG report sheet. I updated the help string to be a bit more specific. Please do let me know if any more info to be added. Thanks. 
___
*[`Readme.md` line 101 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NpKAF1Z8G7W-uR-i4zR:-NpKSTPB5yYl4j4zFcUT:b-9evahz) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9d0d3e09be1b82427e77a11c303b059c6824c56d/Readme.md#L101)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

same as above to add more detail
</blockquote></details>

Updated as above
___
*[`resources/home/dnanexus/generate_workbook/generate_workbook.py` line 242 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NpKAIqw5448KKAWtn5t:-NpKSct34q0PqoUfLAuz:b-9evahz) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9d0d3e09be1b82427e77a11c303b059c6824c56d/resources/home/dnanexus/generate_workbook/generate_workbook.py#L242)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

as above
</blockquote></details>

Updated as above
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 848 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NopooQH38rryQLWCnib:-NpKTQ9A88ehI3DV19zJ:b-32uqjp) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e708f37ab563cac8f1c684c6abbf6c0b0e36d372/resources/home/dnanexus/generate_workbook/utils/excel.py#L848)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

ahhh okay, if either of those columns aren't present (i.e. if we reun the app without `--add_comment_column` specified, then `comment_col` would be None and your `cell_to_unlock` would end up being `None2`), I assume this would raise an error? should you check that was is retured from `get_col_letter()` is not None first?
</blockquote></details>

added `if` statement to see if the `comment_col` is `None` or not. For `interpreted_col`, I think it will be always present as long as it's dias and it's the first variant sheet. 
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 32 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-NpKANHd3LbV0-lRBNKE:-NpKSeSh2WTBd1OvLy4a:b-qkeukk) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9d0d3e09be1b82427e77a11c303b059c6824c56d/resources/home/dnanexus/generate_workbook/utils/excel.py#L32)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can this have a comment to mention where it's being used and what for
</blockquote></details>

added the comment as suggested.

**Review by jethror1 — APPROVED** [review]
> Reviewed 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163)* status: 3 of 5 files reviewed, 1 unresolved discussion

**Review by jethror1 — APPROVED** [review]
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wintun12)

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 584 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163#-Np0PPvl9FUu2DT7AN_S:-NpKWnpwACt0jmTmSecs:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9d0d3e09be1b82427e77a11c303b059c6824c56d/resources/home/dnanexus/generate_workbook/utils/excel.py#L584)):*
<details><summary><i>Previously, wintun12 wrote…</i></summary><blockquote>

Here I rename `report_` as `interpret_` as Wook asked me to do so.
</blockquote></details>

Done

**Pull request merged**
