### PR TITLE
In 500 make additional sheet consistent with main vcf

### PR DESCRIPTION
**Pull request by Aisha-D**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/200)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/200)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @Aisha-D)

___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 742 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/200#-O9UGi7VCt9gTWWiAt3F:-O9UGi7VCt9gTWWiAt3G:b-wc1asg) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/91b48d01c454f8ca1735de468a67e34039299404/resources/home/dnanexus/generate_workbook/utils/vcf.py#L742)):*
> ```Python
> 
> 
>     def order_columns(self, vcfs) -> None:
> ```

return type is now incorrect



_Code quote:_
```Python
None
```
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 746 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/200#-O9UGjoLALp-KZjrgwEF:-O9UGjoLALp-KZjrgwEG:b-39vxn4) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/91b48d01c454f8ca1735de468a67e34039299404/resources/home/dnanexus/generate_workbook/utils/vcf.py#L746)):*
> ```Python
>         Reorder columns by specified order from `--reorder` argument, any not
>         specified will retain original order after reorder columns
> ```

Missing Parameters and Returns from docstring
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 962 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/200#-O9UGpA07KmwgKE5nG8v:-O9UGpA07KmwgKE5nG8w:bf4d0zg) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/91b48d01c454f8ca1735de468a67e34039299404/resources/home/dnanexus/generate_workbook/utils/vcf.py#L962)):*
> ```Python
> 
> 
>     def percent_af(self, vcfs):
> ```

missing return type hint



_Code quote:_
```Python
self, vcfs):
```
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 965 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/200#-O9UGo6_AY_03zghPrFo:-O9UGo6_AY_03zghPrFp:b-39vxn4) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/91b48d01c454f8ca1735de468a67e34039299404/resources/home/dnanexus/generate_workbook/utils/vcf.py#L965)):*
> ```Python
>         """
>         Finds the column with "AF" and will convert the number format
>         to percent
> ```

Missing Parameters and Returns from docstring
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 975 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/200#-O9UGrpf7O58O7XWNag3:-O9UGrpf7O58O7XWNag4:b-iyvhz2) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/91b48d01c454f8ca1735de468a67e34039299404/resources/home/dnanexus/generate_workbook/utils/vcf.py#L975)):*
> ```Python
> 
>             vcfs[idx] = vcf
>         
> ```

whitespace

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/200)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 742 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/200#-O9UGi7VCt9gTWWiAt3F:-O9UIJsz1xGLb3uHE9Jr:bb7f2mf) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/91b48d01c454f8ca1735de468a67e34039299404/resources/home/dnanexus/generate_workbook/utils/vcf.py#L742)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

return type is now incorrect
</blockquote></details>

done
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 746 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/200#-O9UGjoLALp-KZjrgwEF:-O9UIc5H3hpE5tZhLlju:bb7f2mf) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/91b48d01c454f8ca1735de468a67e34039299404/resources/home/dnanexus/generate_workbook/utils/vcf.py#L746)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

Missing Parameters and Returns from docstring
</blockquote></details>

done
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 962 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/200#-O9UGpA07KmwgKE5nG8v:-O9UIsGHBrn00CoOk0WF:bb7f2mf) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/91b48d01c454f8ca1735de468a67e34039299404/resources/home/dnanexus/generate_workbook/utils/vcf.py#L962)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

missing return type hint
</blockquote></details>

done
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 965 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/200#-O9UGo6_AY_03zghPrFo:-O9UIrco17gHf-Jt8FGX:bb7f2mf) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/91b48d01c454f8ca1735de468a67e34039299404/resources/home/dnanexus/generate_workbook/utils/vcf.py#L965)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

Missing Parameters and Returns from docstring
</blockquote></details>

done

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/200)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 975 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/200#-O9UGrpf7O58O7XWNag3:-O9UKKBL18_9SlDTQrBg:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/91b48d01c454f8ca1735de468a67e34039299404/resources/home/dnanexus/generate_workbook/utils/vcf.py#L975)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

whitespace
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/200#-:-O9ULV7fCqK9Mn7bkFoH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
