### PR TITLE
update summary and interpret sheets

### PR DESCRIPTION
**Pull request by wintun12**
Changes:

- Increase unlocked row from 200 to 500 in all sheets
- update the PID box in the summary sheet
- swap between BA1 and BS1 rows in interpret sheets

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/174)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/174)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @wintun12)

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 483 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/174#-NraBPyW1kaJ_zyiy_Zl:-NraBPyXCgDclMRZV0wB:b-cpvie) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/a19ce7cfd68f8731b16026ad1ca7edbb86335ed6/resources/home/dnanexus/generate_workbook/utils/excel.py#L483)):*
> ```Python
> 
>         # write center reporting section tables
>         self.summary.cell(2, 1).value = "Lab no."
> ```

are they intending to fill the lab number in cell B2? should "Lab no." text be in cell B2 for them to fill in B3 in line with the names?




_Code quote:_
```Python
self.summary.cell(2, 1).value = "Lab no."
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 487 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/174#-NraC-F1A4tWWbVTYUD0:-NraC-F20Zo28vo1zENC:b-h9mn1p) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/a19ce7cfd68f8731b16026ad1ca7edbb86335ed6/resources/home/dnanexus/generate_workbook/utils/excel.py#L487)):*
> ```Python
>         self.summary.cell(2, 4).value = "Last name"
>         self.summary.cell(4, 1).value = "Number checked"
>         self.summary.cell(5, 1).value = "Summary coverage"
> ```

is this meant to be copy pasting the clinical text from the coverage report? If so, do they want some of these cells merging ? Whats the use case for it?



_Code quote:_
```Python
"Summary coverage"
```

**Review by wintun12 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/174)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 483 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/174#-NraBPyW1kaJ_zyiy_Zl:-NraDH8uB4PE3s7m5pp8:b-svpky9) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/a19ce7cfd68f8731b16026ad1ca7edbb86335ed6/resources/home/dnanexus/generate_workbook/utils/excel.py#L483)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

are they intending to fill the lab number in cell B2? should "Lab no." text be in cell B2 for them to fill in B3 in line with the names?

</blockquote></details>

Lab no., first name and last name are supposed to be copied/pasted into A3, C3 and D3. They copy the whole thing (all those three cells) from another place (not sure where), but they need B3 just empty and unlocked so that they can make a direct copy in that way. B2 has nothing to be filled in. It's locked.  The e screenshot from the scientists attached. In their example, N24xxxx will go to A3, John to C3 and Smith to D3. But to be able to copy them all together, one empty cell (B3) is required. 

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 487 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/174#-NraC-F1A4tWWbVTYUD0:-NraFWd59zYMeSCjnafp:bp3vl2r) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/a19ce7cfd68f8731b16026ad1ca7edbb86335ed6/resources/home/dnanexus/generate_workbook/utils/excel.py#L487)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this meant to be copy pasting the clinical text from the coverage report? If so, do they want some of these cells merging ? Whats the use case for it?
</blockquote></details>

As screenshot attached, there are always three lines of summary coverage they want to copy. Again they want to copy all together from somewhere. Since there are empty lines between (in the original), they need some empty rows so that they can do copy/paste all together. For example, they want to copy the whole summary coverage in B5. Then, the first line of summary (ATM xxx)  will appear in B5, the 2nd line  of summary (Genes with coverage xxx) will appear in B7 and the third line (100% of this panel) will appear in B9. The lines in between are just empty and they want that way.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/174)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @wintun12)

___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 483 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/174#-NraBPyW1kaJ_zyiy_Zl:-NraIvUG4jtDZWpSZNFi:btj4dbx) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/a19ce7cfd68f8731b16026ad1ca7edbb86335ed6/resources/home/dnanexus/generate_workbook/utils/excel.py#L483)):*
<details><summary><i>Previously, wintun12 wrote…</i></summary><blockquote>

Lab no., first name and last name are supposed to be copied/pasted into A3, C3 and D3. They copy the whole thing (all those three cells) from another place (not sure where), but they need B3 just empty and unlocked so that they can make a direct copy in that way. B2 has nothing to be filled in. It's locked.  The e screenshot from the scientists attached. In their example, N24xxxx will go to A3, John to C3 and Smith to D3. But to be able to copy them all together, one empty cell (B3) is required. 

</blockquote></details>

ahhh that makes complete sense, thanks!

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/174)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wintun12)

**Pull request merged**
