### PR TITLE
IN-501 add report text

### PR DESCRIPTION
**Pull request by Aisha-D**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/179)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
can you please add details to the readme on the new input

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/179#-:-NtL7abJ-OUyfQh9m4Bi:b-5lm7uz)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @Aisha-D)

___
*[`resources/home/dnanexus/generate_workbook/generate_workbook.py` line 319 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/179#-NtL6XOz1clCD_Sl5JCG:-NtL6XOz1clCD_Sl5JCH:b-2dkeg2) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c0d2b5a75ddaade0354a83c61890e4f65e7d2769/resources/home/dnanexus/generate_workbook/generate_workbook.py#L319)):*
> ```Python
>             help=('Makes a report summary to be appened as the last column'
>             )
>         )
> ```

this also needs exposing as the app input in the same way as others



_Code quote:_
```Python
        parser.add_argument(
            '--report_text', action='store_true',
            help=('Makes a report summary to be appened as the last column'
            )
        )
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1721 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/179#-NtL6i_jCIZE5s2Lg7do:-NtL6i_jCIZE5s2Lg7dp:b-6fac61) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c0d2b5a75ddaade0354a83c61890e4f65e7d2769/resources/home/dnanexus/generate_workbook/utils/excel.py#L1721)):*
> ```Python
>             for row in curr_worksheet.iter_cols():
>                 column_name = row[0].value
>                 # Check if the row has"Report text" in first column
> ```

missing space



_Code quote:_
```Python
s"
```
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1731 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/179#-NtL746SEodqW1OeTXMZ:-NtL746SEodqW1OeTXM_:b-58so6z) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c0d2b5a75ddaade0354a83c61890e4f65e7d2769/resources/home/dnanexus/generate_workbook/utils/excel.py#L1731)):*
> ```Python
> 
>             # re-use the set_widths colum
>             # self.set_widths(curr_worksheet, col)
> ```

needed?



_Code quote:_
```Python
            # re-use the set_widths colum
            # self.set_widths(curr_worksheet, col)
```
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 188 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/179#-NtL786gEnFmPG7Fj-gs:-NtL786gEnFmPG7Fj-gt:btl7k0n) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c0d2b5a75ddaade0354a83c61890e4f65e7d2769/resources/home/dnanexus/generate_workbook/utils/vcf.py#L188)):*
> ```Python
>         if self.args.report_text:
>             # make a report_text column and append to end of df
>             self.make_report_text()
> ```

put this before `if self.args.reorder()` will allow it to be shifted in position with the column ordering input



_Code quote:_
```Python
        if self.args.report_text:
            # make a report_text column and append to end of df
            self.make_report_text()
```
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 879 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/179#-NtL7VTt25BhVbvpj1eT:-NtL7VTt25BhVbvpj1eU:b-1nuoxk) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c0d2b5a75ddaade0354a83c61890e4f65e7d2769/resources/home/dnanexus/generate_workbook/utils/vcf.py#L879)):*
> ```Python
>         for idx, vcf in enumerate(self.vcfs):
>             vcf['Report_text'] = vcf.apply(
>             lambda x: (
> ```

is this a direct copy paste from the handler app?



_Code quote:_
```Python
lambda x: (
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/179)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/generate_workbook.py` line 319 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/179#-NtL6XOz1clCD_Sl5JCG:-NtMNUsG6hK5Iu0BrLKo:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c0d2b5a75ddaade0354a83c61890e4f65e7d2769/resources/home/dnanexus/generate_workbook/generate_workbook.py#L319)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this also needs exposing as the app input in the same way as others
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1721 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/179#-NtL6i_jCIZE5s2Lg7do:-NtMOhFk-NGMaTb6q-Yt:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c0d2b5a75ddaade0354a83c61890e4f65e7d2769/resources/home/dnanexus/generate_workbook/utils/excel.py#L1721)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

missing space
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/utils/excel.py` line 1731 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/179#-NtL746SEodqW1OeTXMZ:-NtMOgq67LDpAUa9UcSX:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c0d2b5a75ddaade0354a83c61890e4f65e7d2769/resources/home/dnanexus/generate_workbook/utils/excel.py#L1731)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

needed?
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 879 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/179#-NtL7VTt25BhVbvpj1eT:-NtMOiiW0J0wbAbhbTRA:b-rmxvc9) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c0d2b5a75ddaade0354a83c61890e4f65e7d2769/resources/home/dnanexus/generate_workbook/utils/vcf.py#L879)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this a direct copy paste from the handler app?
</blockquote></details>

yes. I need to amend this cause its annotating the introns in correctly

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/179)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 188 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/179#-NtL786gEnFmPG7Fj-gs:-NtMOqB78Pw3rLckWb1L:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c0d2b5a75ddaade0354a83c61890e4f65e7d2769/resources/home/dnanexus/generate_workbook/utils/vcf.py#L188)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

put this before `if self.args.reorder()` will allow it to be shifted in position with the column ordering input
</blockquote></details>

Done.

**Review by Aisha-D — COMMENTED** [review]
done.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/179#-:-NtMk6St0fBM2JMGxStA:b-7rl0jd)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 1 of 4 files at r3, 4 of 5 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/179)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
