### PR TITLE
IN-503 Option to have AF presented as a decimal or percentage

### PR DESCRIPTION
**Pull request by Aisha-D**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/183)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/183)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @Aisha-D)

___
*[`dxapp.json` line 281 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/183#-NtQzqbI1mUH2Yqt7pAW:-NtQzqbI1mUH2Yqt7pAX:b-izwgws) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9509d03bca26e1a1fe8589920f03602580410a2d/dxapp.json#L281)):*
> ```JSON
>     },
>     {
>       "name": "AF",
> ```

could we have this lowercase for consistency, and for it to be more descriptive (i.e. `af_format`)



_Code quote:_
```JSON
AF
```
___
*[`dxapp.json` line 282 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/183#-NtQznKX0Ou2dDVTm1Lh:-NtQznKX0Ou2dDVTm1Li:b2an33s) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9509d03bca26e1a1fe8589920f03602580410a2d/dxapp.json#L282)):*
> ```JSON
>     {
>       "name": "AF",
>       "label": "lock_sheet",
> ```

did you mean to include this?



_Code quote:_
```JSON
"label": "lock_sheet",
```
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 887 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/183#-NtR-9YV3XZIJWb9Dp80:-NtR-9YV3XZIJWb9Dp81:b628kx4) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9509d03bca26e1a1fe8589920f03602580410a2d/resources/home/dnanexus/generate_workbook/utils/vcf.py#L887)):*
> ```Python
>         for vcf in self.vcfs:
>             vcf['AF'] = vcf['AF'].astype(np.float16)
>             vcf['AF'] = vcf['AF'].map(lambda n: '{:,.1%}'.format(n))
> ```

if AF is not present, I assume this will break? can you add a check first like:
```
if not 'AF' in vcf.columns:
    continue
```
then it will continue to the next vcf dataframe if that column is absent



_Code quote:_
```Python
        for vcf in self.vcfs:
            vcf['AF'] = vcf['AF'].astype(np.float16)
            vcf['AF'] = vcf['AF'].map(lambda n: '{:,.1%}'.format(n))
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/183)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`dxapp.json` line 281 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/183#-NtQzqbI1mUH2Yqt7pAW:-NtR3vEn6ePJ7T_WSH23:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9509d03bca26e1a1fe8589920f03602580410a2d/dxapp.json#L281)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

could we have this lowercase for consistency, and for it to be more descriptive (i.e. `af_format`)
</blockquote></details>

Done.
___
*[`dxapp.json` line 282 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/183#-NtQznKX0Ou2dDVTm1Lh:-NtR3vVn84-Rfmlz_QhY:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9509d03bca26e1a1fe8589920f03602580410a2d/dxapp.json#L282)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

did you mean to include this?
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 887 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/183#-NtR-9YV3XZIJWb9Dp80:-NtR4Ul39qwF0tJ34WOs:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/9509d03bca26e1a1fe8589920f03602580410a2d/resources/home/dnanexus/generate_workbook/utils/vcf.py#L887)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if AF is not present, I assume this will break? can you add a check first like:
```
if not 'AF' in vcf.columns:
    continue
```
then it will continue to the next vcf dataframe if that column is absent
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/183)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`src/code.sh` line 113 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/183#-NtRA2Ye-bBeSDT_cZCp:-NtRA2Ye-bBeSDT_cZCq:bk3hlkb) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/aa59ec9bf42bd7d12f463a8853fe5a150e65bbb1/src/code.sh#L113)):*
> ```Shell
>     if [ "$lock_sheet" == true ]; then args+="--lock_sheet "; fi
>     if [ "$report_text" == true ]; then args+="--report_text" fi
>     if [ "$af_format"]; then args+="--af_format ${af_format}" fi
> ```

can you add a trailing space before the closing quote, so if another arg is added after it will not be joined



_Code quote:_
```Shell
}"
```

**Review by jethror1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/183#-:-NtRCJVtBGb8ZafzaP4y:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/183)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
