### PR TITLE
Add yet another column to make Jon happy pt. 3

### PR DESCRIPTION
**Pull request by jethror1**
Add another optional input for adding a simple concat column of chrom, pos, ref and alt

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/149)

### CODE REVIEW

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/149)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/generate_workbook.py` line 307 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/149#-N_-Cpr201JrBBERhJfq:-N_-Cpr330Gl9iyd5c9w:b-7sn8sx) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/92f84bb57a74a13a0afc862c92e764a43e29daab/resources/home/dnanexus/generate_workbook/generate_workbook.py#L307)):*
> ```Python
>             '--add_raw_change', action='store_true',
>             help=(
>                 'If true, will add a column named rawChange of concatenation '
> ```

`rawChange` ? because i don't the rest of the sentence makes sense?

**Comment by jethror1** [comment]
> > Reviewed 6 of 6 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/149)_ status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)
> 
> _[`resources/home/dnanexus/generate_workbook/generate_workbook.py` line 307 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/149#-N_-Cpr201JrBBERhJfq:-N_-Cpr330Gl9iyd5c9w:b-7sn8sx) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/92f84bb57a74a13a0afc862c92e764a43e29daab/resources/home/dnanexus/generate_workbook/generate_workbook.py#L307)):_
> 
> > ```python
> >             '--add_raw_change', action='store_true',
> >             help=(
> >                 'If true, will add a column named rawChange of concatenation '
> > ```
> 
> `rawChange` ? because i don't the rest of the sentence makes sense?

done

**Review by Yu-jinKim — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/149)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

**Review by Yu-jinKim — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/149)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
