### PR TITLE
Cosmic handling

### PR DESCRIPTION
**Pull request by RSWilson1**
- Added handling for VEP fields with duplicates due to multiple transcripts.
- Added hyperlinks for COSMIC field.

Screenshot:
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/134)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/134)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @RSWilson1)

___
*[`resources/home/dnanexus/generate_workbook/utils/columns.py` line 36 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/134#-NURnokj-JQr3vtGV-2D:-NURnokj-JQr3vtGV-2E:b4livcz) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/a5b05c937c8f2b3be7860cd04da96c1863817501/resources/home/dnanexus/generate_workbook/utils/columns.py#L36)):*
> ```Python
> 
> 
>     def unique_vep(self, vcf_df):
> ```

why remove the return type?



_Code quote:_
```Python
def unique_vep(self, vcf_df):
```
___
*[`resources/home/dnanexus/generate_workbook/utils/columns.py` line 58 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/134#-NURnj7j-ON9srCnX57-:-NURnj7j-ON9srCnX570:b-7270es) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/a5b05c937c8f2b3be7860cd04da96c1863817501/resources/home/dnanexus/generate_workbook/utils/columns.py#L58)):*
> ```Python
>         for col in csq_columns:
>             vcf_df[col] = vcf_df[col].apply(
>                 lambda x: ' & '.join(sorted(set(x.split('&')))) if isinstance(x, str) else x
> ```

can we remove spaces around the `&`



_Code quote:_
```Python
' & '
```

**Review by RSWilson1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/134)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`resources/home/dnanexus/generate_workbook/utils/columns.py` line 36 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/134#-NURnokj-JQr3vtGV-2D:-NURuib-70qJOF8WzRwW:b-eklsoo) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/a5b05c937c8f2b3be7860cd04da96c1863817501/resources/home/dnanexus/generate_workbook/utils/columns.py#L36)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why remove the return type?
</blockquote></details>

yeah no need, added this back
___
*[`resources/home/dnanexus/generate_workbook/utils/columns.py` line 58 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/134#-NURnj7j-ON9srCnX57-:-NURupkz2w14SqgpMAqD:bvg7ph5) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/a5b05c937c8f2b3be7860cd04da96c1863817501/resources/home/dnanexus/generate_workbook/utils/columns.py#L58)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can we remove spaces around the `&`
</blockquote></details>

sure, the function I based this on had spaces around it so I wasn't sure if that was the preferred formatting. Changed to just '&'.

**Review by jethror1 — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/134)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RSWilson1)

**Comment by RSWilson1** [comment]
Fixed test for decipher which had a typo (https://github.com/eastgenomics/eggd_generate_variant_workbook/pull/134/commits/22cb7b5de54001487f552ca4ba6fe988067a7b60) and problem with vcf_handler by adding 'add_comment_column=False'.
image

**Pull request merged**
