### PR TITLE
URA-899 request to change prev count ac to be formatted as prev count ac an

### PR DESCRIPTION
**Pull request by Aisha-D**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202)* status: 1 of 4 files reviewed, 10 unresolved discussions (waiting on @Aisha-D)

___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 392 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMjm033PCF9nS29ZM6:-OAMjm033PCF9nS29ZM7:bjs641d) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L392)):*
> ```Python
>         )
> 
>     def test_join_columns_right(self):
> ```

can you add a test also when we have comma as the delimiter that it is correct?



_Code quote:_
```Python
 def test_join_columns_right(self):
```
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 413 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMjSD14Avw4zLnxqlh:-OAMjSD14Avw4zLnxqli:b-5nx1os) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L413)):*
> ```Python
> 
> 
>     def test_join_columns_many_column_seperators(self):
> ```

when you're testing for edge cases being caught and errors correctly raised it can be nice to make the test name more explicit, something like `test_type_error_raised_when_too_many_separators_provided`, this makes debugging much easier if / when many tests fail



_Code quote:_
```Python
test_join_columns_many_column_seperators
```
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 426 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMj7TvDtTzePvJ2XnE:-OAMj7TwCE_N4palC9In:b-n9637i) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L426)):*
> ```Python
>         'requires the seperator of columns to be comma '
>         '(e.g --join_columns="Prev_Count=CSQ_Prev_Count_AC,/,CSQ_Prev_Count_NS"). '
>         'Expects either two or three minimum commas in string.')
> ```

if you're wanting to test that the error is raised with the expected message, you can use the `match` param in `pytest.raises` to do it directly instead of needing an additional assert: https://github.com/eastgenomics/eggd_dias_batch/blob/eea364eb0b8b00f11f5c1094a92739eed499a1e7/resources/home/dnanexus/dias_batch/tests/test_utils.py#L874



_Code quote:_
```Python
        with pytest.raises(TypeError) as excinfo:
            vcf_handler.joining_columns(vcf_handler.vcfs)
        assert str(excinfo.value) == ('WARNING: --join_columns '
        'requires the seperator of columns to be comma '
        '(e.g --join_columns="Prev_Count=CSQ_Prev_Count_AC,/,CSQ_Prev_Count_NS"). '
        'Expects either two or three minimum commas in string.')
```
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 1119 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMk6ZN2YQswKw1xP6b:-OAMk6ZN2YQswKw1xP6c:b-yrgxmv) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/utils/vcf.py#L1119)):*
> ```Python
>             # assumption is user provides header with "=" as seperator, so there
>             # should be one equal sign
>             if join.count('=') != 1:
> ```

what happens if we want to use `=` to join the fields to look like what we get in an INFO field?



_Code quote:_
```Python
if join.count('=') != 1:
```
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 1126 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMkQOe4lB3TT_YUvex:-OAMkQOf86hqpNzLFqpT:b-5y161b) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/utils/vcf.py#L1126)):*
when you're splitting into 2 you can unpack these into 2 variables directly:
```
>>> foo, bar = 'a=b'.split('=')
>>> foo
'a'
>>> bar
'b'
```



_Code quote:_
```Python
            joins_dict["header"] = join.split("=")[0]
            column_to_join=join.split("=")[1]
```
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 1128 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMkkdRDIboZ1IiYaAk:-OAMkkdRDIboZ1IiYaAl:b-s57plf) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/utils/vcf.py#L1128)):*
> ```Python
>             column_to_join=join.split("=")[1]
>             # assumption is user provides "," as seperator, so there
>             # should be two or three semi colons (three due to column seperator being chosen as comma)
> ```

should this be comma?



_Code quote:_
```Python
semi colons
```
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 1129 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMn6qe0N9oLdQjFzC1:-OAMn6qf7rtPmvzSUwnI:bsl3wm8) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/utils/vcf.py#L1129)):*
> ```Python
>             # assumption is user provides "," as seperator, so there
>             # should be two or three semi colons (three due to column seperator being chosen as comma)
>             if join.count(',') != 2 |  join.count(',') != 3:
> ```

this is fine but if you end up with more conditions to check, it can be better to format as `if join.count(',') in (2, 3, ...)`



_Code quote:_
```Python
if join.count(',') != 2 |  join.count(',') != 3:
```
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 1142 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMlOUWDd7x84bOfH9l:-OAMlOUX5sTB_zuGmmrS:b-qdgllc) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/utils/vcf.py#L1142)):*
as above this can be unpacked directly with one split:
```
>>> d = {}
>>> s = 'foo,bar,baz'
>>> d['a'], d['b'], d['c'] = s.split(',')
>>> d
{'a': 'foo', 'b': 'bar', 'c': 'baz'}
```



_Code quote:_
```Python
                joins_dict["join_1"] = column_to_join.split(',')[0]
                joins_dict["seperator"] = column_to_join.split(',')[1]
                joins_dict["join_2"] = column_to_join.split(',')[2]
```
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 1151 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMmKaJ4t93SvMocO-N:-OAMmKaJ4t93SvMocO-O:b-4sq11z) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/utils/vcf.py#L1151)):*
similar to above this could be one split with:
```
>>> d = {}
>>> s = 'foo,bar,baz'
>>> d['a'], d['b'] = s.split(',')[0::2]
>>> d
{'a': 'foo', 'b': 'baz'}
```
then add your separator



_Code quote:_
```Python
                joins_dict["join_1"] = column_to_join.split(',')[0]
                joins_dict["seperator"] = ","
                joins_dict["join_2"] = column_to_join.split(',')[3]
```
___
*[`src/code.sh` line 114 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMmuBT2DSOlyuv8A4p:-OAMmuBT2DSOlyuv8A4q:b-9ysg3k) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/src/code.sh#L114)):*
> ```Shell
>     if [ "$report_text" == true ]; then args+="--report_text "; fi
>     if [ "$af_format" ]; then args+="--af_format ${af_format} "; fi
>     if [ "$join_columns" ]; then args+="--join_columns ${join_columns} "; fi
> ```

can you add a trailing space here so if more args are added in the future someone doesn't have to remember to add one



_Code quote:_
```Shell
${join_columns} "
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202)* status: 1 of 4 files reviewed, 10 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 413 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMjSD14Avw4zLnxqlh:-OAMp0bC-GcPYRX2pDn9:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L413)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

when you're testing for edge cases being caught and errors correctly raised it can be nice to make the test name more explicit, something like `test_type_error_raised_when_too_many_separators_provided`, this makes debugging much easier if / when many tests fail
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 426 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMj7TvDtTzePvJ2XnE:-OAMp1cg57Ve0QKifnUu:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L426)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if you're wanting to test that the error is raised with the expected message, you can use the `match` param in `pytest.raises` to do it directly instead of needing an additional assert: https://github.com/eastgenomics/eggd_dias_batch/blob/eea364eb0b8b00f11f5c1094a92739eed499a1e7/resources/home/dnanexus/dias_batch/tests/test_utils.py#L874
</blockquote></details>

Done.

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202)* status: 1 of 4 files reviewed, 10 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 1119 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMk6ZN2YQswKw1xP6b:-OAMqF13CC01W8nsSfxq:b-rotjrg) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/utils/vcf.py#L1119)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what happens if we want to use `=` to join the fields to look like what we get in an INFO field?
</blockquote></details>

good point, might need to handle this sort of request
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 1126 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMkQOe4lB3TT_YUvex:-OAMqDtp2I6ZqPynvVS0:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/utils/vcf.py#L1126)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

when you're splitting into 2 you can unpack these into 2 variables directly:
```
>>> foo, bar = 'a=b'.split('=')
>>> foo
'a'
>>> bar
'b'
```
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 1128 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMkkdRDIboZ1IiYaAk:-OAMqUN2Da3j2y7-heYf:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/utils/vcf.py#L1128)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should this be comma?
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 1129 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMn6qe0N9oLdQjFzC1:-OAMqn6E1Kp8DslDjb8Y:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/utils/vcf.py#L1129)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this is fine but if you end up with more conditions to check, it can be better to format as `if join.count(',') in (2, 3, ...)`
</blockquote></details>

Done.
___
*[`src/code.sh` line 114 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMmuBT2DSOlyuv8A4p:-OAMr03v8h06RsN2AW8s:b-r3uqhc) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/src/code.sh#L114)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you add a trailing space here so if more args are added in the future someone doesn't have to remember to add one
</blockquote></details>

add space after ${join_columns} ? I think there is a space there before the quote ?

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202)* status: 1 of 4 files reviewed, 10 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 392 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMjm033PCF9nS29ZM6:-OAMrc2l254d_XhFtgyC:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L392)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you add a test also when we have comma as the delimiter that it is correct?
</blockquote></details>

Done.

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202)* status: 1 of 4 files reviewed, 10 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 1142 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMlOUWDd7x84bOfH9l:-OAMtujt1MnZJpBKOU8l:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/utils/vcf.py#L1142)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

as above this can be unpacked directly with one split:
```
>>> d = {}
>>> s = 'foo,bar,baz'
>>> d['a'], d['b'], d['c'] = s.split(',')
>>> d
{'a': 'foo', 'b': 'bar', 'c': 'baz'}
```
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 1151 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMmKaJ4t93SvMocO-N:-OAMtvPC4c50VerxnW_J:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/utils/vcf.py#L1151)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

similar to above this could be one split with:
```
>>> d = {}
>>> s = 'foo,bar,baz'
>>> d['a'], d['b'] = s.split(',')[0::2]
>>> d
{'a': 'foo', 'b': 'baz'}
```
then add your separator
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Aisha-D)

___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 1119 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMk6ZN2YQswKw1xP6b:-OAN3QrHDMe3b9MfZeS0:b-mgcs32) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/utils/vcf.py#L1119)):*
you should be able to handle it by checking for at least one `=` here, then below where you split to get the header change it to `joins_dict["header"], column_to_join = join.split("=", `)` which will just split on first occurrence

```
>>> s = 'foo=bar,=,baz'
>>> header, columns = s.split('=', 1)
>>> header
'foo'
>>> columns
'bar,=,baz'
```

would be worth a test for this too, or possibly parametrize your test to  test with many different delimiters and check them all
___
*[`src/code.sh` line 114 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMmuBT2DSOlyuv8A4p:-OAN48El6x2nbiKiGMMA:bq73wui) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/src/code.sh#L114)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

add space after ${join_columns} ? I think there is a space there before the quote ?
</blockquote></details>

oh so there is, sorry reviewable is wrapping weirdly and it didn't look like there was

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 1119 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OAMk6ZN2YQswKw1xP6b:-OANNFXE-lUG9ADAkolp:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/748e1f6175c30d0f19109b46f1756f2874e64084/resources/home/dnanexus/generate_workbook/utils/vcf.py#L1119)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

you should be able to handle it by checking for at least one `=` here, then below where you split to get the header change it to `joins_dict["header"], column_to_join = join.split("=", `)` which will just split on first occurrence

```
>>> s = 'foo=bar,=,baz'
>>> header, columns = s.split('=', 1)
>>> header
'foo'
>>> columns
'bar,=,baz'
```

would be worth a test for this too, or possibly parametrize your test to  test with many different delimiters and check them all
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 426 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OANgevg7-ZNhaVmhu68:-OANgevg7-ZNhaVmhu69:bkgvtc9) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e35cec846577e218d74abf3d118959f4ae83228d/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L426)):*
unless you need the index of where your item is in the iterable, there's no need to loop over the length and select, you can just do it directly with:
```
separators = '!#$%&'()*+,-./:;<=>?@[]^_`{|}~'

for sep in separators:
    ...
```

if you do need both the index and item then `enumerate` is what you want:
```
>>> separators = "!#$%&'()*+,-./:;<=>?@[]^_`{|}~"
>>> for idx, sep in enumerate(separators):
...     print(idx, sep)
... 
0 !
1 #
2 $
3 %
4 &
5 '
6 (
7 )
8 *
9 +
10 ,
11 -
12 .
13 /
14 :
15 ;
16 <
17 =
18 >
19 ?
20 @
21 [
22 ]
23 ^
24 _
25 `
26 {
27 |
28 }
29 ~
```



_Code quote:_
```Python
        for i in range(len(punctuation)):
            vcf_handler = self.read_vcf()
            p = punctuation[i]
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 426 at r7](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-OANgevg7-ZNhaVmhu68:-OANikLk-Tg_JvYEqU-F:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/e35cec846577e218d74abf3d118959f4ae83228d/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L426)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

unless you need the index of where your item is in the iterable, there's no need to loop over the length and select, you can just do it directly with:
```
separators = '!#$%&'()*+,-./:;<=>?@[]^_`{|}~'

for sep in separators:
    ...
```

if you do need both the index and item then `enumerate` is what you want:
```
>>> separators = "!#$%&'()*+,-./:;<=>?@[]^_`{|}~"
>>> for idx, sep in enumerate(separators):
...     print(idx, sep)
... 
0 !
1 #
2 $
3 %
4 &
5 '
6 (
7 )
8 *
9 +
10 ,
11 -
12 .
13 /
14 :
15 ;
16 <
17 =
18 >
19 ?
20 @
21 [
22 ]
23 ^
24 _
25 `
26 {
27 |
28 }
29 ~
```
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202#-:-OANohX77zIrdoHbEbFo:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
